### PR TITLE
fix: fix explore state actions initial explore state filters and the clear filters action (#60)

### LINKED ISSUE #60: Fix explore state actions initial explore state filters and the clear filters action

### PR DESCRIPTION
**Pull request by frano-m**
Closes #60.

- Explore State Action `ClearFilters` fixes clear all filters button for the entity list.
- Explore State Action `SelectEntityType` updates state values for the selected tab such as `categoryViews` and `categoryGroupConfigs`.
- Explore State Actions `ProcessExploreResponse`, `UpdateFilter`, `UpdateSorting`, and `UpdateColumnVisibility` use the new `updateEntityPageState` function to update the `entityPageState`.
- Initialisation of Explore State fixes the `entityPageState` - the current entity list's `entityPageState`'s `filterState` and `filterCount` are initialised by values from the decoded filter param.

### CODE REVIEW

File: src/providers/exploreState.tsx [hunk 1]
```diff
@@ -371,10 +372,17 @@ function exploreReducer(
      * Clear all filters
      **/
     case ExploreActionKind.ClearFilters: {
+      const filterCount = 0;
+      const filterState: SelectedFilter[] = [];
       return {
         ...state,
-        filterCount: 0,
-        filterState: [],
+        entityPageState: updateEntityPageState(
```
Comment (frano-m) [inline src/providers/exploreState.tsx:379]: `updateEntityPageState` function to update the entity's `entityPageState` with the cleared filter state + count.

File: src/providers/exploreState.tsx [hunk 2]
```diff
@@ -413,13 +421,9 @@ function exploreReducer(
...
         categoryGroupConfigs: entityPageState[tabValue].categoryGroupConfigs,
         categoryViews: nextCategoryViews ?? categoryViews,
-        entityPageState: {
-          ...entityPageState,
-          [tabValue]: {
-            ...entityPageState[tabValue],
-            categoryViews: nextCategoryViews ?? categoryViews,
-          },
-        },
+        entityPageState: updateEntityPageState(tabValue, entityPageState, {
```
Comment (frano-m) [inline src/providers/exploreState.tsx:424]: `updateEntityPageState` function to update the entity's `entityPageState` with the next category views.

File: src/providers/exploreState.tsx [hunk 3]
```diff
@@ -511,35 +516,27 @@ function exploreReducer(
...
-          ...state.entityPageState,
-          [currentEntity]: {
-            ...currentPageState,
-            columnsVisibility: payload,
-          },
-        },
+        entityPageState: updateEntityPageState(
+          state.tabValue,
+          state.entityPageState,
+          { columnsVisibility: payload }
```
Comment (frano-m) [inline src/providers/exploreState.tsx:538]: `updateEntityPageState` function to update the entity's `entityPageState` with the updated `columnsVisibility`.

File: src/providers/exploreState.tsx [hunk 4]
```diff
@@ -511,35 +516,27 @@ function exploreReducer(
...
-          ...state.entityPageState,
-          [currentEntity]: {
-            ...currentPageState,
-            sorting: payload,
-          },
-        },
+        entityPageState: updateEntityPageState(
+          state.tabValue,
+          state.entityPageState,
+          { sorting: payload }
```
Comment (frano-m) [inline src/providers/exploreState.tsx:524]: `updateEntityPageState` function to update the entity's `entityPageState` with the updated `sorting`.

File: src/providers/exploreState.tsx [hunk 5]
```diff
@@ -494,14 +502,11 @@ function exploreReducer(
...
-          [state.tabValue]: {
-            ...state.entityPageState[state.tabValue],
-            filterCount,
-            filterState,
-          },
-        },
+        entityPageState: updateEntityPageState(
+          state.tabValue,
+          state.entityPageState,
+          { filterCount, filterState }
```
Comment (frano-m) [inline src/providers/exploreState.tsx:508]: `updateEntityPageState` function to update the entity's `entityPageState` with the updated `filterCount` and `filterState`.

File: src/providers/exploreState.tsx [hunk 6]
```diff
@@ -461,10 +465,14 @@ function exploreReducer(
       if (payload === state.tabValue) {
         return state;
       }
+      const { entityPageState } = state;
+      const entityState = entityPageState[payload];
       return {
         ...state,
-        filterCount: state.entityPageState[payload].filterCount,
-        filterState: state.entityPageState[payload].filterState,
+        categoryGroupConfigs: entityState.categoryGroupConfigs,
```
Comment (frano-m) [inline src/providers/exploreState.tsx:472]: `SelectEntityType` action should update `entityPageState` values to top level state to keep values in sync.

File: src/providers/exploreState/utils.ts [hunk 7]
```diff
@@ -46,7 +47,10 @@ export function initExploreState(
     ...INITIAL_STATE,
     catalogState: decodedCatalogParam,
     categoryGroupConfigs: entityPageState[entityListType].categoryGroupConfigs,
-    entityPageState: initEntityPageState(config),
+    entityPageState: updateEntityPageState(entityListType, entityPageState, {
```
Comment (frano-m) [inline src/providers/exploreState/utils.ts:50]: The `entityPageState` for the selected entity should be initialised with `filterCount` and `filterState` from the decoded filter param.

**Review by NoopDog — APPROVED** [review]
Super ! Thx
