### PR TITLE
fix: quote values in tsv export when they contain syntactic characters (#314)

### LINKED ISSUE #314: In TSV export, values containing syntactic characters should be quoted

### PR DESCRIPTION
**Pull request by hunterckx**
Closes #314

### CODE REVIEW

File: src/components/Table/common/utils.ts [hunk 1]
```diff
@@ -99,11 +99,16 @@ function formatDataToTSV(data: TableData[][]): string {
     .map((row) => {
       return row
         .map((data) => {
-          // Concatenate array values.
-          if (Array.isArray(data)) {
-            return data.join(", ");
-          }
-          return data;
+          // Use empty string in place of undefined and null.
+          if (data === undefined || data === null) return "";
```
Comment (hunterckx) [inline src/components/Table/common/utils.ts:103]: Apparently `join` automatically converts undefined and null to empty string, so I've added this line to retain that behavior

**Review by NoopDog — APPROVED** [review]
Thx!
