### PR TITLE
fix: add 'rel' attribute to viewsupport component props (#328)

### LINKED ISSUE #328: Add 'rel' attribute to ViewSupport component props

### PR DESCRIPTION
**Pull request by frano-m**
Closes #328.

### CODE REVIEW

File: src/components/Support/components/ViewSupport/types.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import { AnchorHTMLAttributes, ElementType } from "react";
+import { BaseComponentProps } from "../../../types";
+
+export interface ViewSupportProps
+  extends AnchorHTMLAttributes<HTMLAnchorElement>,
+    BaseComponentProps {
+  Icon?: ElementType;
+  url: string;
```
Comment (MillenniumFalconMechanic) [inline src/components/Support/components/ViewSupport/types.ts:8]: Is it possible to use the `href` value on the `AnchorHTMLAttributes` interface instead of adding this `url` value?

Comment (frano-m) [reply src/components/Support/components/ViewSupport/types.ts:8]: Yes!

Comment (frano-m) [reply src/components/Support/components/ViewSupport/types.ts:8]: If we remove url as a prop, it would be a breaking change.

Comment (NoopDog) [reply src/components/Support/components/ViewSupport/types.ts:8]: Hi @frano-m how big a change is it both in the package and in the apps. Breaking change is not a problem, but we don't want to introduce a bunch of churn/other difficulties for this. Ahe the "breaking changes" simple/trivial or no?
